### ISSUE TITLE
Toggle #S

### ISSUE THREAD

**Issue by ask6155** [aerickt/plover-lapwing-aio#1]
Hello,

I'm currently using a YASK board which wires both the S on the right side as the upper S it seems.
So after I setup Lapwing it becomes impossible to type the S as all `S` turn into `#S`
i think this functionality was added for other boards which wire the `S` separately.
Can you please add a toggle to that feature?

**Comment by aerickt** [comment]
> YASK board which wires both the S on the right side as the upper S it seems.

I'm assuming you mean the left `S`? Or am I misunderstanding?
Though, if this is the case, I'm also a bit confused how pressing either `S` key results in `#S` in the paper tape—if both keys are mapped to the upper `S`, then surely they would only output `#`?

In any event, you should be able to fix the key map in Plover. Open configure, and then the machine tab. You can scroll down and tweak the keys.

![Untitled](https://github.com/aerickt/plover-lapwing-aio/assets/52895314/97da1b9a-c2c7-4252-a8c5-7c5c5be1ddfa)

You may have to play around with the settings; I'm not sure exactly what you will need to set for `S1` and `S2` as I'm not familiar with the YASK.

**Comment by ask6155** [comment]
I'm also not sure how pressing the left `S` results in `#S` but that's what was happening.
I set `S1-` as `S` (It was set as `#` as shown) and now it works!

Thank you.
